# icarus56 config

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# bluetooth
CONFIG_BT=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_BLE=y

# rotary encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Power mngmt
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000  # 15 min

# usb
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
